twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        app_default_user_image: '%env(DEFAULT_IMAGE_PATH)%/%env(DEFAULT_USER_IMAGE)%'
        app_default_trick_image: '%env(DEFAULT_IMAGE_PATH)%/%env(DEFAULT_TRICK_IMAGE)%'
        app_menu_logo: '%env(DEFAULT_IMAGE_PATH)%/%env(DEFAULT_MENU_LOGO)%'
        primary_image_carouse: '%env(PRIMARY_IMAGE_CAROUSEL)%'
        DEFAULT_PAGE_TITLE: '%env(DEFAULT_PAGE_TITLE)%'
        DEFAULT_PAGE_DESCRIPTION: '%env(DEFAULT_PAGE_DESCRIPTION)%'
        DEFAULT_PAGE_KEYWORDS: '%env(DEFAULT_PAGE_KEYWORDS)%'
        DEFAULT_UPLOAD_TRICK_IMAGE_PATH: '%env(DEFAULT_UPLOAD_TRICK_IMAGE_PATH)%'


    form_themes:
        - 'Form/vich_fields.html.twig'
        - 'Form/fields.html.twig'
