vich_uploader:
    db_driver: orm

    mappings:
        user_images:
            uri_prefix: '%app.path.user_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.user_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        trick_images:
            uri_prefix: '%app.path.trick_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.trick_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
