easy_admin:
  site_name: 'SnowTricks Administration'
  list:
    title: 'Edit %%entity_label%%s'
    actions:
      - {name: 'edit', icon: 'pencil', label: false}
      - {name: 'delete', icon: 'trash', label: false}

  user:
    display_name: true
    name_property_path: 'userName'
    display_avatar: true

  design:
    menu:
      - {entity: 'User', icon: 'user'}
      - {entity: 'Trick', icon: 'snowflake-o'}
      - {entity: 'Category', icon: 'tag'}