easy_admin:
  entities:
    Trick:
      class: App\Entity\Trick
      list:
        fields:
          - {property: 'id'}
          - {property: 'name', type: 'text'}
          - {property: 'category'}
          - {property: 'createdAt'}
          - {property: 'editedAt'}
          - {property: 'tags'}
          - {property: 'comments'}
          - {property: 'images'}
          - {property: 'videos'}
      form:
        fields:
          - {property: 'name'}
          - {property: 'text'}
          - {property: 'category'}
          - {property: 'tags', type_options: {by_reference: false}}