easy_admin:
  entities:
    Trick:
      class: App\Entity\Trick
      list:
        fields:
          - {property: 'name', type: 'text'}
          - {property: 'category'}
          - {property: 'createdAt'}
          - {property: 'editedAt'}
          - {property: 'tags'}
      form:
        fields:
          - {property: 'name'}
          - {property: 'text'}
          - {property: 'category'}
          - {property: 'tags'}